### ISSUE TITLE
NTP timeserver not syncing right, and can't select 12/24 hour time

### ISSUE THREAD

**Issue by devicemodder** [marciot/esp32-dali-clock#4]
I select NTP timeserver and it always syncs to show 20:00:59, regardless of location. I have to manually set the time every time i power up the ESP32. 

Also, how can i get it to show the time in 12 hour format?

**Comment by marciot** [comment]
@devicemodder: You may want to check the serial console for any errors. I'm guessing it is failing to contact the NTP server.

Currently, the 12-hour format isn't supported. Mostly this is because the original Dali clock doesn't have any sort of PM/AM indicator. It would not be hard to allow a 12-hour format without a PM/AM indicator, although that might be a bit confusing.

**Comment by devicemodder** [comment]
Thanks for getting back to me,  I'll check the console and see what's
happened. As for the am/pm in 12 hour, that isn't really of much concern.
Just as long as I can display the time in 12 hour. Doesn't need to say AM
or PM. What line do I have to modify to achieve this?

**Comment by marciot** [comment]
You would have to modify this function:

https://github.com/marciot/esp32-dali-clock/blob/876abec22265002d74716d47f93a33285a5ca049/esp32-dali-clock/src/dali_clock.cpp#L94

If you consider supporting me on GitHub or Patreon, I would consider making a new release with this feature as a configurable option.

**Comment by devicemodder** [comment]
Thanks, i'll modify that string. it seems like with the NTP location sync, that it isnt actually picking up the location, although i see no errors in the serial console.

**Comment by marciot** [comment]
@devicemodder: I made a new release of the code. I figured out what was wrong with the location code and also added a new checkbox to toggle between 12 and 24 hour mode. Thank you for your feedback and bug report!

**Comment by marciot** [comment]
@devicemodder: If this new release does what you need, feel free to close this ticket!

**Comment by devicemodder** [comment]
Thanks. I appreciate it.
